version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: onlaunch
      POSTGRES_USER: onlaunch
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

  # onlaunch:
  #   build: .
  #   environment:
  #     DATABASE_URL: postgresql://onlaunch:password@db:5432/onlaunch?schema=public
  #   ports:
  #     - 3000:3000
