version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: onlaunch
      POSTGRES_USER: onlaunch
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis-sentinel:
    image: docker.io/bitnami/redis-sentinel:7.2
    volumes:
      - redis-sentinel_data:/bitnami

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-"password"}
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    volumes:
      - redis_data:/usr/share/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-"password"}

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${SMTP_PORT:-1025}:${SMTP_PORT:-1025}
      - 8025:8025

  # onlaunch:
  #   build:
  #     context: .
  #   image: kula/onlaunch:latest
  #   pull_policy: always
  #   environment:
  #     DATABASE_URL: postgresql://onlaunch:password@db:5432/onlaunch?schema=public
  #     NEXTAUTH_SECRET: "this is a secret example"
  #     SMTP_HOST: mailhog
  #     SMTP_PORT: 1025
  #     SMTP_USER: ""
  #     SMTP_PASS: ""
  #     HEALTH_API_KEY: onlaunch-api-key
  #     SIGNUPS_ENABLED: true
  #   ports:
  #     - 3000:3000

volumes:
  redis-sentinel_data:
    driver: local
  redis_data:
    driver: local
