services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: onlaunch
      POSTGRES_USER: onlaunch
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kula.app
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass

  redis-sentinel:
    image: docker.io/bitnami/redis-sentinel:7.4
    volumes:
      - redis-sentinel_data:/bitnami

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-"password"}
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    volumes:
      - redis_data:/usr/share/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-"password"}

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${SMTP_PORT:-1025}:${SMTP_PORT:-1025}
      - 8025:8025

  # onlaunch:
  #   build:
  #     context: .
  #   image: kula/onlaunch:latest
  #   pull_policy: always
  #   environment:
  #     DATABASE_URL: postgresql://onlaunch:password@db:5432/onlaunch?schema=public
  #     HEALTH_API_KEY: onlaunch-api-key
  #     NEXTAUTH_SECRET: "this is a secret example"
  #     REDIS_ENABLED: true
  #     REDIS_PASSWORD: ${REDIS_PASSWORD:-"password"}
  #     # SENTRY_DSN:
  #     SENTRY_DEBUG: true
  #     SIGNUPS_ENABLED: true
  #     SMTP_HOST: mailhog
  #     SMTP_PASS: ""
  #     SMTP_PORT: ${SMTP_PORT:-1025}
  #     SMTP_USER: ""
  #   ports:
  #     - 3000:3000

configs:
  pgpass:
    content: db:5432:*:onlaunch:password
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "My Local Postgres DB",
        "Host": "db",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "onlaunch",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis-sentinel_data:
    driver: local
  redis_data:
    driver: local
