version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: onlaunch
      POSTGRES_USER: onlaunch
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  redis-sentinel:
    image: docker.io/bitnami/redis-sentinel:7.2
    volumes:
      - redis-sentinel_data:/bitnami

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-"password"}
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    volumes:
      - redis_data:/usr/share/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-"password"}

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${SMTP_PORT:-1025}:${SMTP_PORT:-1025}
      - 8025:8025

  onlaunch:
    build:
      context: .
    image: kula/onlaunch:latest
    pull_policy: always
    environment:
      DATABASE_URL: postgresql://onlaunch:password@db:5432/onlaunch?schema=public
      HEALTH_API_KEY: onlaunch-api-key
      NEXTAUTH_SECRET: "this is a secret example"
      REDIS_ENABLED: true
      REDIS_PASSWORD: ${REDIS_PASSWORD:-"password"}
      SENTRY_DSN: https://f986d33b5f1f485f8e27a82031b11c98@o997061.ingest.sentry.io/4505046260580352
      SIGNUPS_ENABLED: true
      SMTP_HOST: mailhog
      SMTP_PASS: ""
      SMTP_PORT: ${SMTP_PORT:-1025}
      SMTP_USER: ""
    ports:
      - 3000:3000

volumes:
  postgres_data:
    driver: local
  redis-sentinel_data:
    driver: local
  redis_data:
    driver: local
