export enum SimpleFiltersLanguage {
  ALL = "ALL",

  AA = "aa",
  AB = "ab",
  AE = "ae",
  AF = "af",
  AK = "ak",
  AM = "am",
  AN = "an",
  AR = "ar",
  AS = "as",
  AV = "av",
  AY = "ay",
  AZ = "az",
  BA = "ba",
  BE = "be",
  BG = "bg",
  BH = "bh",
  BI = "bi",
  BM = "bm",
  BN = "bn",
  BO = "bo",
  BR = "br",
  BS = "bs",
  CA = "ca",
  CE = "ce",
  CH = "ch",
  CO = "co",
  CR = "cr",
  CS = "cs",
  CU = "cu",
  CV = "cv",
  CY = "cy",
  DA = "da",
  DE = "de",
  DV = "dv",
  DZ = "dz",
  EE = "ee",
  EL = "el",
  EN = "en",
  EO = "eo",
  ES = "es",
  ET = "et",
  EU = "eu",
  FA = "fa",
  FF = "ff",
  FI = "fi",
  FJ = "fj",
  FO = "fo",
  FR = "fr",
  FY = "fy",
  GA = "ga",
  GD = "gd",
  GL = "gl",
  GN = "gn",
  GU = "gu",
  GV = "gv",
  HA = "ha",
  HE = "he",
  HI = "hi",
  HO = "ho",
  HR = "hr",
  HT = "ht",
  HU = "hu",
  HY = "hy",
  HZ = "hz",
  IA = "ia",
  ID = "id",
  IE = "ie",
  IG = "ig",
  II = "ii",
  IK = "ik",
  IO = "io",
  IS = "is",
  IT = "it",
  IU = "iu",
  JA = "ja",
  JV = "jv",
  KA = "ka",
  KG = "kg",
  KI = "ki",
  KJ = "kj",
  KK = "kk",
  KL = "kl",
  KM = "km",
  KN = "kn",
  KO = "ko",
  KR = "kr",
  KS = "ks",
  KU = "ku",
  KV = "kv",
  KW = "kw",
  KY = "ky",
  LA = "la",
  LB = "lb",
  LG = "lg",
  LI = "li",
  LN = "ln",
  LO = "lo",
  LT = "lt",
  LU = "lu",
  LV = "lv",
  MG = "mg",
  MH = "mh",
  MI = "mi",
  MK = "mk",
  ML = "ml",
  MN = "mn",
  MR = "mr",
  MS = "ms",
  MT = "mt",
  MY = "my",
  NA = "na",
  NB = "nb",
  ND = "nd",
  NE = "ne",
  NG = "ng",
  NL = "nl",
  NN = "nn",
  NO = "no",
  NR = "nr",
  NV = "nv",
  NY = "ny",
  OC = "oc",
  OJ = "oj",
  OM = "om",
  OR = "or",
  OS = "os",
  PA = "pa",
  PI = "pi",
  PL = "pl",
  PS = "ps",
  PT = "pt",
  QU = "qu",
  RM = "rm",
  RN = "rn",
  RO = "ro",
  RU = "ru",
  RW = "rw",
  SA = "sa",
  SC = "sc",
  SD = "sd",
  SE = "se",
  SG = "sg",
  SI = "si",
  SK = "sk",
  SL = "sl",
  SM = "sm",
  SN = "sn",
  SO = "so",
  SQ = "sq",
  SR = "sr",
  SS = "ss",
  ST = "st",
  SU = "su",
  SV = "sv",
  SW = "sw",
  TA = "ta",
  TE = "te",
  TG = "tg",
  TH = "th",
  TI = "ti",
  TK = "tk",
  TL = "tl",
  TN = "tn",
  TO = "to",
  TR = "tr",
  TS = "ts",
  TT = "tt",
  TW = "tw",
  TY = "ty",
  UG = "ug",
  UK = "uk",
  UR = "ur",
  UZ = "uz",
  VE = "ve",
  VI = "vi",
  VO = "vo",
  WA = "wa",
  WO = "wo",
  XH = "xh",
  YI = "yi",
  YO = "yo",
  ZA = "za",
  ZH = "zh",
  ZU = "zu",
}

// List of ISO-639-1 language codes
const languageLookup: {
  [key in SimpleFiltersLanguage]: {
    code: string;
    longName: string;
    shortName?: string;
  };
} = {
  [SimpleFiltersLanguage.ALL]: { code: "all", longName: "All" },
  [SimpleFiltersLanguage.AA]: { code: "aa", longName: "Afar" },
  [SimpleFiltersLanguage.AB]: { code: "ab", longName: "Abkhazian" },
  [SimpleFiltersLanguage.AE]: { code: "ae", longName: "Avestan" },
  [SimpleFiltersLanguage.AF]: { code: "af", longName: "Afrikaans" },
  [SimpleFiltersLanguage.AK]: { code: "ak", longName: "Akan" },
  [SimpleFiltersLanguage.AM]: { code: "am", longName: "Amharic" },
  [SimpleFiltersLanguage.AN]: { code: "an", longName: "Aragonese" },
  [SimpleFiltersLanguage.AR]: { code: "ar", longName: "Arabic" },
  [SimpleFiltersLanguage.AS]: { code: "as", longName: "Assamese" },
  [SimpleFiltersLanguage.AV]: { code: "av", longName: "Avaric" },
  [SimpleFiltersLanguage.AY]: { code: "ay", longName: "Aymara" },
  [SimpleFiltersLanguage.AZ]: { code: "az", longName: "Azerbaijani" },
  [SimpleFiltersLanguage.BA]: { code: "ba", longName: "Bashkir" },
  [SimpleFiltersLanguage.BE]: { code: "be", longName: "Belarusian" },
  [SimpleFiltersLanguage.BG]: { code: "bg", longName: "Bulgarian" },
  [SimpleFiltersLanguage.BH]: { code: "bh", longName: "Bihari languages" },
  [SimpleFiltersLanguage.BI]: { code: "bi", longName: "Bislama" },
  [SimpleFiltersLanguage.BM]: { code: "bm", longName: "Bambara" },
  [SimpleFiltersLanguage.BN]: { code: "bn", longName: "Bengali" },
  [SimpleFiltersLanguage.BO]: { code: "bo", longName: "Tibetan" },
  [SimpleFiltersLanguage.BR]: { code: "br", longName: "Breton" },
  [SimpleFiltersLanguage.BS]: { code: "bs", longName: "Bosnian" },
  [SimpleFiltersLanguage.CA]: { code: "ca", longName: "Catalan; Valencian" },
  [SimpleFiltersLanguage.CE]: { code: "ce", longName: "Chechen" },
  [SimpleFiltersLanguage.CH]: { code: "ch", longName: "Chamorro" },
  [SimpleFiltersLanguage.CO]: { code: "co", longName: "Corsican" },
  [SimpleFiltersLanguage.CR]: { code: "cr", longName: "Cree" },
  [SimpleFiltersLanguage.CS]: { code: "cs", longName: "Czech" },
  [SimpleFiltersLanguage.CU]: {
    code: "cu",
    longName:
      "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
    shortName: "Church Slavonic",
  },
  [SimpleFiltersLanguage.CV]: { code: "cv", longName: "Chuvash" },
  [SimpleFiltersLanguage.CY]: { code: "cy", longName: "Welsh" },
  [SimpleFiltersLanguage.DA]: { code: "da", longName: "Danish" },
  [SimpleFiltersLanguage.DE]: { code: "de", longName: "German" },
  [SimpleFiltersLanguage.DV]: {
    code: "dv",
    longName: "Divehi; Dhivehi; Maldivian",
  },
  [SimpleFiltersLanguage.DZ]: { code: "dz", longName: "Dzongkha" },
  [SimpleFiltersLanguage.EE]: { code: "ee", longName: "Ewe" },
  [SimpleFiltersLanguage.EL]: {
    code: "el",
    longName: "Greek, Modern (1453-)",
    shortName: "Greek",
  },
  [SimpleFiltersLanguage.EN]: { code: "en", longName: "English" },
  [SimpleFiltersLanguage.EO]: { code: "eo", longName: "Esperanto" },
  [SimpleFiltersLanguage.ES]: {
    code: "es",
    longName: "Spanish; Castilian",
    shortName: "Spanish",
  },
  [SimpleFiltersLanguage.ET]: { code: "et", longName: "Estonian" },
  [SimpleFiltersLanguage.EU]: { code: "eu", longName: "Basque" },
  [SimpleFiltersLanguage.FA]: { code: "fa", longName: "Persian" },
  [SimpleFiltersLanguage.FF]: { code: "ff", longName: "Fulah" },
  [SimpleFiltersLanguage.FI]: { code: "fi", longName: "Finnish" },
  [SimpleFiltersLanguage.FJ]: { code: "fj", longName: "Fijian" },
  [SimpleFiltersLanguage.FO]: { code: "fo", longName: "Faroese" },
  [SimpleFiltersLanguage.FR]: { code: "fr", longName: "French" },
  [SimpleFiltersLanguage.FY]: { code: "fy", longName: "Western Frisian" },
  [SimpleFiltersLanguage.GA]: { code: "ga", longName: "Irish" },
  [SimpleFiltersLanguage.GD]: {
    code: "gd",
    longName: "Gaelic; Scottish Gaelic",
    shortName: "Scottish Gaelic",
  },
  [SimpleFiltersLanguage.GL]: { code: "gl", longName: "Galician" },
  [SimpleFiltersLanguage.GN]: { code: "gn", longName: "Guarani" },
  [SimpleFiltersLanguage.GU]: { code: "gu", longName: "Gujarati" },
  [SimpleFiltersLanguage.GV]: { code: "gv", longName: "Manx" },
  [SimpleFiltersLanguage.HA]: { code: "ha", longName: "Hausa" },
  [SimpleFiltersLanguage.HE]: { code: "he", longName: "Hebrew" },
  [SimpleFiltersLanguage.HI]: { code: "hi", longName: "Hindi" },
  [SimpleFiltersLanguage.HO]: { code: "ho", longName: "Hiri Motu" },
  [SimpleFiltersLanguage.HR]: { code: "hr", longName: "Croatian" },
  [SimpleFiltersLanguage.HT]: {
    code: "ht",
    longName: "Haitian; Haitian Creole",
    shortName: "Haitian Creole",
  },
  [SimpleFiltersLanguage.HU]: { code: "hu", longName: "Hungarian" },
  [SimpleFiltersLanguage.HY]: { code: "hy", longName: "Armenian" },
  [SimpleFiltersLanguage.HZ]: { code: "hz", longName: "Herero" },
  [SimpleFiltersLanguage.IA]: {
    code: "ia",
    longName: "Interlingua (International Auxiliary Language Association)",
    shortName: "Interlingua",
  },
  [SimpleFiltersLanguage.ID]: { code: "id", longName: "Indonesian" },
  [SimpleFiltersLanguage.IE]: {
    code: "ie",
    longName: "Interlingue; Occidental",
    shortName: "Interlingue",
  },
  [SimpleFiltersLanguage.IG]: { code: "ig", longName: "Igbo" },
  [SimpleFiltersLanguage.II]: {
    code: "ii",
    longName: "Sichuan Yi; Nuosu",
    shortName: "Nuosu",
  },
  [SimpleFiltersLanguage.IK]: { code: "ik", longName: "Inupiaq" },
  [SimpleFiltersLanguage.IO]: { code: "io", longName: "Ido" },
  [SimpleFiltersLanguage.IS]: { code: "is", longName: "Icelandic" },
  [SimpleFiltersLanguage.IT]: { code: "it", longName: "Italian" },
  [SimpleFiltersLanguage.IU]: { code: "iu", longName: "Inuktitut" },
  [SimpleFiltersLanguage.JA]: { code: "ja", longName: "Japanese" },
  [SimpleFiltersLanguage.JV]: { code: "jv", longName: "Javanese" },
  [SimpleFiltersLanguage.KA]: { code: "ka", longName: "Georgian" },
  [SimpleFiltersLanguage.KG]: { code: "kg", longName: "Kongo" },
  [SimpleFiltersLanguage.KI]: {
    code: "ki",
    longName: "Kikuyu; Gikuyu",
    shortName: "Kikuyu",
  },
  [SimpleFiltersLanguage.KJ]: {
    code: "kj",
    longName: "Kuanyama; Kwanyama",
    shortName: "Kwanyama",
  },
  [SimpleFiltersLanguage.KK]: { code: "kk", longName: "Kazakh" },
  [SimpleFiltersLanguage.KL]: {
    code: "kl",
    longName: "Kalaallisut; Greenlandic",
    shortName: "Greenlandic",
  },
  [SimpleFiltersLanguage.KM]: {
    code: "km",
    longName: "Central Khmer",
    shortName: "Khmer",
  },
  [SimpleFiltersLanguage.KN]: { code: "kn", longName: "Kannada" },
  [SimpleFiltersLanguage.KO]: { code: "ko", longName: "Korean" },
  [SimpleFiltersLanguage.KR]: { code: "kr", longName: "Kanuri" },
  [SimpleFiltersLanguage.KS]: { code: "ks", longName: "Kashmiri" },
  [SimpleFiltersLanguage.KU]: { code: "ku", longName: "Kurdish" },
  [SimpleFiltersLanguage.KV]: { code: "kv", longName: "Komi" },
  [SimpleFiltersLanguage.KW]: { code: "kw", longName: "Cornish" },
  [SimpleFiltersLanguage.KY]: {
    code: "ky",
    longName: "Kirghiz; Kyrgyz",
    shortName: "Kyrgyz",
  },
  [SimpleFiltersLanguage.LA]: { code: "la", longName: "Latin" },
  [SimpleFiltersLanguage.LB]: {
    code: "lb",
    longName: "Luxembourgish; Letzeburgesch",
    shortName: "Luxembourgish",
  },
  [SimpleFiltersLanguage.LG]: { code: "lg", longName: "Ganda" },
  [SimpleFiltersLanguage.LI]: {
    code: "li",
    longName: "Limburgan; Limburger; Limburgish",
    shortName: "Limburgish",
  },
  [SimpleFiltersLanguage.LN]: { code: "ln", longName: "Lingala" },
  [SimpleFiltersLanguage.LO]: { code: "lo", longName: "Lao" },
  [SimpleFiltersLanguage.LT]: { code: "lt", longName: "Lithuanian" },
  [SimpleFiltersLanguage.LU]: { code: "lu", longName: "Luba-Katanga" },
  [SimpleFiltersLanguage.LV]: { code: "lv", longName: "Latvian" },
  [SimpleFiltersLanguage.MG]: { code: "mg", longName: "Malagasy" },
  [SimpleFiltersLanguage.MH]: { code: "mh", longName: "Marshallese" },
  [SimpleFiltersLanguage.MI]: { code: "mi", longName: "Maori" },
  [SimpleFiltersLanguage.MK]: { code: "mk", longName: "Macedonian" },
  [SimpleFiltersLanguage.ML]: { code: "ml", longName: "Malayalam" },
  [SimpleFiltersLanguage.MN]: { code: "mn", longName: "Mongolian" },
  [SimpleFiltersLanguage.MR]: { code: "mr", longName: "Marathi" },
  [SimpleFiltersLanguage.MS]: { code: "ms", longName: "Malay" },
  [SimpleFiltersLanguage.MT]: { code: "mt", longName: "Maltese" },
  [SimpleFiltersLanguage.MY]: { code: "my", longName: "Burmese" },
  [SimpleFiltersLanguage.NA]: { code: "na", longName: "Nauru" },
  [SimpleFiltersLanguage.NB]: {
    code: "nb",
    longName: "Bokmål, Norwegian; Norwegian Bokmål",
    shortName: "Norwegian Bokmål",
  },
  [SimpleFiltersLanguage.ND]: {
    code: "nd",
    longName: "Ndebele, North; North Ndebele",
    shortName: "North Ndebele",
  },
  [SimpleFiltersLanguage.NE]: { code: "ne", longName: "Nepali" },
  [SimpleFiltersLanguage.NG]: { code: "ng", longName: "Ndonga" },
  [SimpleFiltersLanguage.NL]: {
    code: "nl",
    longName: "Dutch; Flemish",
    shortName: "Dutch",
  },
  [SimpleFiltersLanguage.NN]: {
    code: "nn",
    longName: "Norwegian Nynorsk; Nynorsk, Norwegian",
    shortName: "Norwegian Nynorsk",
  },
  [SimpleFiltersLanguage.NO]: { code: "no", longName: "Norwegian" },
  [SimpleFiltersLanguage.NR]: {
    code: "nr",
    longName: "Ndebele, South; South Ndebele",
    shortName: "South Ndebele",
  },
  [SimpleFiltersLanguage.NV]: {
    code: "nv",
    longName: "Navajo; Navaho",
    shortName: "Navajo",
  },
  [SimpleFiltersLanguage.NY]: {
    code: "ny",
    longName: "Chichewa; Chewa; Nyanja",
    shortName: "Chichewa",
  },
  [SimpleFiltersLanguage.OC]: {
    code: "oc",
    longName: "Occitan (post 1500)",
    shortName: "Occitan",
  },
  [SimpleFiltersLanguage.OJ]: { code: "oj", longName: "Ojibwa" },
  [SimpleFiltersLanguage.OM]: { code: "om", longName: "Oromo" },
  [SimpleFiltersLanguage.OR]: { code: "or", longName: "Oriya" },
  [SimpleFiltersLanguage.OS]: {
    code: "os",
    longName: "Ossetian; Ossetic",
    shortName: "Ossetian",
  },
  [SimpleFiltersLanguage.PA]: {
    code: "pa",
    longName: "Panjabi; Punjabi",
    shortName: "Punjabi",
  },
  [SimpleFiltersLanguage.PI]: { code: "pi", longName: "Pali" },
  [SimpleFiltersLanguage.PL]: { code: "pl", longName: "Polish" },
  [SimpleFiltersLanguage.PS]: {
    code: "ps",
    longName: "Pushto; Pashto",
    shortName: "Pashto",
  },
  [SimpleFiltersLanguage.PT]: { code: "pt", longName: "Portuguese" },
  [SimpleFiltersLanguage.QU]: { code: "qu", longName: "Quechua" },
  [SimpleFiltersLanguage.RM]: { code: "rm", longName: "Romansh" },
  [SimpleFiltersLanguage.RN]: { code: "rn", longName: "Rundi" },
  [SimpleFiltersLanguage.RO]: {
    code: "ro",
    longName: "Romanian; Moldavian; Moldovan",
    shortName: "Romanian",
  },
  [SimpleFiltersLanguage.RU]: { code: "ru", longName: "Russian" },
  [SimpleFiltersLanguage.RW]: { code: "rw", longName: "Kinyarwanda" },
  [SimpleFiltersLanguage.SA]: { code: "sa", longName: "Sanskrit" },
  [SimpleFiltersLanguage.SC]: { code: "sc", longName: "Sardinian" },
  [SimpleFiltersLanguage.SD]: { code: "sd", longName: "Sindhi" },
  [SimpleFiltersLanguage.SE]: {
    code: "se",
    longName: "Northern Sami",
    shortName: "Sami",
  },
  [SimpleFiltersLanguage.SG]: { code: "sg", longName: "Sango" },
  [SimpleFiltersLanguage.SI]: {
    code: "si",
    longName: "Sinhala; Sinhalese",
    shortName: "Sinhala",
  },
  [SimpleFiltersLanguage.SK]: { code: "sk", longName: "Slovak" },
  [SimpleFiltersLanguage.SL]: { code: "sl", longName: "Slovenian" },
  [SimpleFiltersLanguage.SM]: { code: "sm", longName: "Samoan" },
  [SimpleFiltersLanguage.SN]: { code: "sn", longName: "Shona" },
  [SimpleFiltersLanguage.SO]: { code: "so", longName: "Somali" },
  [SimpleFiltersLanguage.SQ]: { code: "sq", longName: "Albanian" },
  [SimpleFiltersLanguage.SR]: { code: "sr", longName: "Serbian" },
  [SimpleFiltersLanguage.SS]: { code: "ss", longName: "Swati" },
  [SimpleFiltersLanguage.ST]: {
    code: "st",
    longName: "Sotho, Southern",
    shortName: "Southern Sotho",
  },
  [SimpleFiltersLanguage.SU]: { code: "su", longName: "Sundanese" },
  [SimpleFiltersLanguage.SV]: { code: "sv", longName: "Swedish" },
  [SimpleFiltersLanguage.SW]: { code: "sw", longName: "Swahili" },
  [SimpleFiltersLanguage.TA]: { code: "ta", longName: "Tamil" },
  [SimpleFiltersLanguage.TE]: { code: "te", longName: "Telugu" },
  [SimpleFiltersLanguage.TG]: { code: "tg", longName: "Tajik" },
  [SimpleFiltersLanguage.TH]: { code: "th", longName: "Thai" },
  [SimpleFiltersLanguage.TI]: { code: "ti", longName: "Tigrinya" },
  [SimpleFiltersLanguage.TK]: { code: "tk", longName: "Turkmen" },
  [SimpleFiltersLanguage.TL]: { code: "tl", longName: "Tagalog" },
  [SimpleFiltersLanguage.TN]: { code: "tn", longName: "Tswana" },
  [SimpleFiltersLanguage.TO]: {
    code: "to",
    longName: "Tonga (Tonga Islands)",
    shortName: "Tongan",
  },
  [SimpleFiltersLanguage.TR]: { code: "tr", longName: "Turkish" },
  [SimpleFiltersLanguage.TS]: { code: "ts", longName: "Tsonga" },
  [SimpleFiltersLanguage.TT]: { code: "tt", longName: "Tatar" },
  [SimpleFiltersLanguage.TW]: { code: "tw", longName: "Twi" },
  [SimpleFiltersLanguage.TY]: { code: "ty", longName: "Tahitian" },
  [SimpleFiltersLanguage.UG]: {
    code: "ug",
    longName: "Uighur; Uyghur",
    shortName: "Uyghur",
  },
  [SimpleFiltersLanguage.UK]: { code: "uk", longName: "Ukrainian" },
  [SimpleFiltersLanguage.UR]: { code: "ur", longName: "Urdu" },
  [SimpleFiltersLanguage.UZ]: { code: "uz", longName: "Uzbek" },
  [SimpleFiltersLanguage.VE]: { code: "ve", longName: "Venda" },
  [SimpleFiltersLanguage.VI]: { code: "vi", longName: "Vietnamese" },
  [SimpleFiltersLanguage.VO]: { code: "vo", longName: "Volapük" },
  [SimpleFiltersLanguage.WA]: { code: "wa", longName: "Walloon" },
  [SimpleFiltersLanguage.WO]: { code: "wo", longName: "Wolof" },
  [SimpleFiltersLanguage.XH]: { code: "xh", longName: "Xhosa" },
  [SimpleFiltersLanguage.YI]: { code: "yi", longName: "Yiddish" },
  [SimpleFiltersLanguage.YO]: { code: "yo", longName: "Yoruba" },
  [SimpleFiltersLanguage.ZA]: {
    code: "za",
    longName: "Zhuang; Chuang",
    shortName: "Zhuang",
  },
  [SimpleFiltersLanguage.ZH]: { code: "zh", longName: "Chinese" },
  [SimpleFiltersLanguage.ZU]: { code: "zu", longName: "Zulu" },
};

export function displayTextForSimpleFiltersLanguage(
  language: SimpleFiltersLanguage,
) {
  return (
    languageLookup[language].shortName ?? languageLookup[language].longName
  );
}
