import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'

import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';


const fetcher = (...args) => fetch(...args).then((res) => res.json())

export default function Home() {
  const { data, error } = useSWR('/api/frontend/v0.1/apps', fetcher)
  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>OnLaunch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Apps</h1>
          <Table sx={{ minWidth: 650 }} aria-label="simple table">
              <TableHead>
                  <TableCell>App Name</TableCell>
                  <TableCell></TableCell>
              </TableHead>
              <TableBody>
                  {
                      data.map((app, index) => {
                          return (
                              <TableRow key={index}>
                                  <TableCell>
                                      {app.name}
                                  </TableCell>
                                  <TableCell>
                                      {index}
                                  </TableCell>
                              </TableRow>
                          )
                      })
                  }
              </TableBody>
          </Table>

      </main>
    </>
  )
}
