export enum MessageRuleSystemVariable {
  BUNDLE_ID = "BUNDLE_ID",
  BUNDLE_VERSION = "BUNDLE_VERSION",
  LOCALE = "LOCALE",
  LOCALE_LANGUAGE_CODE = "LOCALE_LANGUAGE_CODE",
  LOCALE_REGION_CODE = "LOCALE_REGION_CODE",
  PACKAGE_NAME = "PACKAGE_NAME",
  PLATFORM_NAME = "PLATFORM_NAME",
  PLATFORM_VERSION = "PLATFORM_VERSION",
  RELEASE_VERSION = "RELEASE_VERSION",
  VERSION_CODE = "VERSION_CODE",
  VERSION_NAME = "VERSION_NAME",
}
