# ----
# Site

title: OnLaunch - Documentation
baseurl: https://kula-app.github.io/OnLaunch/

# -----
# Build

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -------------------
# Markdown Processing

markdown: kramdown
kramdown:
  input: GFM
