# ----
# Site

title: OnLaunch - Documentation
url: "https://kula-app.github.io/OnLaunch/"

# -----
# Build

timezone: Etc/UTC

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -------------------
# Markdown Processing

markdown: kramdown
kramdown:
  input: GFM
