# ----
# Site

title: OnLaunch - Documentation

# -----
# Build

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -------------------
# Markdown Processing

markdown: kramdown
kramdown:
  input: GFM
