title: OnLaunch - Documentation
description: OnLaunch is a service allowing app developers to notify app users about updates, warnings and maintenance.
remote_theme: CloudCannon/base-jekyll-template

markdown: kramdown
kramdown:
  input: GFM
