name: Build Lint Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Caching Yarn Dependencies
        uses: actions/cache@v3
        timeout-minutes: 10
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Caching Yarn Dependencies
        uses: actions/cache@v3
        timeout-minutes: 10
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Caching Yarn Dependencies
        uses: actions/cache@v3
        timeout-minutes: 10
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test:ci

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          name: codecov-umbrella
          flags: unittests
          fail_ci_if_error: true

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
    services:
      postgres:
        image: postgres
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Caching Yarn Dependencies
        uses: actions/cache@v3
        timeout-minutes: 10
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install cypress
        run: yarn cypress install

      - name: Build app used in E2E tests
        run: yarn build

      - name: Run Tests
        run: yarn test:e2e:ci
